In [2]:
import pandas as pd,numpy as np

In [3]:
df = pd.read_csv("spam.csv", encoding='latin1' )
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [5]:
df= df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis = 1)

In [6]:

df.reset_index(drop =True)

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
df = df.rename(columns={'v1': 'Category',"v2" : "Message"})

In [8]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [10]:
df["spam"] = df.Category.apply(lambda x : 1 if x=="spam" else 0)

In [11]:
df.drop("Category",axis = 1)

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568              Will Ì_ b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_test, X_train, y_test, y_train = train_test_split(df.Message,df.spam,train_size=0.2)

In [14]:

print(X_test.shape)

(1114,)


In [15]:
print(X_train.shape)

(4458,)


In [16]:
y_train.shape

(4458,)

In [17]:
X_train[1]

'Ok lar... Joking wif u oni...'

In [18]:
y_train[1]

0

In [19]:
from sklearn.feature_extraction.text import CountVectorizer # to convert into text into vector

In [20]:
v = CountVectorizer()
X_train_cv= v.fit_transform(X_train.values)

In [34]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
X_train_cv.shape

(4458, 7726)

In [37]:
v.get_feature_names_out()[6798]

'the'

In [24]:
v.vocabulary_

{'very': 7250,
 'strange': 6483,
 'and': 967,
 'are': 1058,
 'watching': 7379,
 'the': 6798,
 '2nd': 403,
 'one': 4923,
 'now': 4832,
 'but': 1587,
 'in': 3639,
 'bed': 1303,
 'sweet': 6629,
 'dreams': 2460,
 'miss': 4498,
 'might': 4460,
 'come': 1913,
 'by': 1600,
 'tonight': 6948,
 'then': 6810,
 'if': 3600,
 'my': 4655,
 'class': 1838,
 'lets': 4073,
 'out': 4992,
 'early': 2522,
 'just': 3869,
 'buy': 1590,
 'pizza': 5204,
 'meat': 4401,
 'lovers': 4217,
 'or': 4958,
 'supreme': 6598,
 'get': 3131,
 'to': 6916,
 'pick': 5178,
 'yes': 7653,
 'last': 4015,
 'practice': 5334,
 'probably': 5401,
 'not': 4818,
 'still': 6453,
 'going': 3186,
 'over': 5005,
 'some': 6258,
 'stuff': 6512,
 'here': 3412,
 'hi': 3426,
 'happy': 3342,
 'new': 4744,
 'year': 7642,
 'dont': 2425,
 'mean': 4393,
 'intrude': 3718,
 'can': 1640,
 'you': 7670,
 'pls': 5234,
 'let': 4072,
 'me': 4390,
 'know': 3952,
 'how': 3524,
 'much': 4623,
 'tuition': 7053,
 'paid': 5032,
 'semester': 5973,
 'this': 6837,
 'i

In [25]:
X_train_np =X_train_cv.toarray()

In [29]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
np.where(X_train_np[0] != 0)

(array([ 403,  967, 1058, 1303, 1587, 2460, 3639, 4498, 4832, 4923, 6483,
        6629, 6798, 7250, 7379], dtype=int64),)

In [31]:
X_train[:4][5177]

"Very strange.  and  are watching the 2nd one now but i'm in bed. Sweet dreams, miss u "

In [36]:
X_train_np[0][6798]

1

In [39]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [40]:
X_test_cv = v.transform(X_test)

In [42]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.96      0.91      0.94       148

    accuracy                           0.98      1114
   macro avg       0.98      0.95      0.96      1114
weighted avg       0.98      0.98      0.98      1114



In [43]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]



In [44]:
emails_cv  = v.transform(emails)
model.predict(emails_cv)

array([0, 1], dtype=int64)

In [45]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [47]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [48]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.96      0.91      0.94       148

    accuracy                           0.98      1114
   macro avg       0.98      0.95      0.96      1114
weighted avg       0.98      0.98      0.98      1114

