In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
one_hot("amazing restaurant",30)

[20, 25]

In [9]:
vocab_size = 30

encoded_reviews =[one_hot(d,vocab_size) for d in reviews
                 ]
encoded_reviews

[[16, 19],
 [20, 25],
 [5, 29],
 [26, 3, 12],
 [2, 9, 15],
 [2, 19],
 [25, 9, 3],
 [4, 6],
 [4, 21],
 [5, 8]]

In [11]:
# make all in same dimentaion

max_length = 3
padded_reviews = pad_sequences(encoded_reviews,maxlen = max_length,padding ="post")
print(padded_reviews)

[[16 19  0]
 [20 25  0]
 [ 5 29  0]
 [26  3 12]
 [ 2  9 15]
 [ 2 19  0]
 [25  9  3]
 [ 4  6  0]
 [ 4 21  0]
 [ 5  8  0]]


In [18]:
embeded_vector_size =4
model = Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation ="sigmoid"))


In [19]:
X =padded_reviews
y=sentiment

In [20]:
model.compile(optimizer ="adam",loss = "binary_crossentropy",metrics = ["accuracy"])

In [21]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.fit(X,y,epochs=10,verbose=0)

In [26]:
loss,accuracy =model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 250ms/step - loss: 0.6747 - accuracy: 0.9000


0.8999999761581421

In [28]:
model.get_layer("embedding").get_weights()

[array([[ 0.02228306, -0.02733442,  0.03916399,  0.00593022],
        [-0.03971695, -0.00437291,  0.00852519,  0.01001643],
        [ 0.0372525 , -0.00315609,  0.02913126,  0.02718527],
        [-0.05989155,  0.01640265,  0.00389305,  0.05000108],
        [ 0.04315505, -0.01036798,  0.03867523, -0.00059735],
        [ 0.00265378,  0.02656536,  0.03744922, -0.01324896],
        [ 0.02281025, -0.0197744 , -0.05879378,  0.01839682],
        [ 0.00839658,  0.01069114,  0.01515671,  0.03869971],
        [ 0.00888169,  0.01655013, -0.02800155, -0.02874117],
        [ 0.00586308, -0.01865325, -0.02567773, -0.02496734],
        [ 0.01344353, -0.04370093, -0.00829213, -0.03301441],
        [ 0.00914504, -0.04464848, -0.04370524,  0.01381185],
        [-0.00580711,  0.03646167,  0.02523759, -0.0523531 ],
        [-0.01435109, -0.03592272, -0.01625841, -0.04502715],
        [ 0.03969917,  0.04732004,  0.02827125,  0.01536791],
        [ 0.0580941 , -0.02445668, -0.05773865,  0.02499679],
        